local _, MDT = ...
local L = MDT.L

---Spells offered in the map text icon picker, names are english search aliases
---the picker shows the spell names of the client language
---verified against retail 12.1.0, bloodlust effects and shroud come first
MDT.presetTextSpellCategories = {
  { key = "groupcd", title = L["Group Cooldowns"] },
  { key = "external", title = L["Externals"] },
  { key = "defensive", title = L["Personal Defensives"] },
  { key = "cc", title = L["Crowd Control"] },
  { key = "interrupt", title = L["Interrupts"] },
  { key = "dispel", title = L["Dispels"] },
}

MDT.presetTextSpells = {
  --groupcd
  { id = 2825, name = "Bloodlust", class = "SHAMAN", category = "groupcd" },
  { id = 32182, name = "Heroism", class = "SHAMAN", category = "groupcd" },
  { id = 80353, name = "Time Warp", class = "MAGE", category = "groupcd" },
  { id = 264667, name = "Primal Rage", class = "HUNTER", category = "groupcd" },
  { id = 390386, name = "Fury of the Aspects", class = "EVOKER", category = "groupcd" },
  { id = 466904, name = "Harrier's Cry", class = "HUNTER", category = "groupcd" },
  { id = 1243972, name = "Void-Touched Drums", class = "GENERAL", category = "groupcd" },
  { id = 114018, name = "Shroud of Concealment", class = "ROGUE", category = "groupcd" },
  { id = 51052, name = "Anti-Magic Zone", class = "DEATHKNIGHT", category = "groupcd" },
  { id = 61999, name = "Raise Ally", class = "DEATHKNIGHT", category = "groupcd" },
  { id = 196718, name = "Darkness", class = "DEMONHUNTER", category = "groupcd" },
  { id = 740, name = "Tranquility", class = "DRUID", category = "groupcd" },
  { id = 20484, name = "Rebirth", class = "DRUID", category = "groupcd" },
  { id = 106898, name = "Stampeding Roar", class = "DRUID", category = "groupcd" },
  { id = 363534, name = "Rewind", class = "EVOKER", category = "groupcd" },
  { id = 359816, name = "Dream Flight", class = "EVOKER", category = "groupcd" },
  { id = 374227, name = "Zephyr", class = "EVOKER", category = "groupcd" },
  { id = 374968, name = "Time Spiral", class = "EVOKER", category = "groupcd" },
  { id = 414664, name = "Mass Invisibility", class = "MAGE", category = "groupcd" },
  { id = 115310, name = "Revival", class = "MONK", category = "groupcd" },
  { id = 388615, name = "Restoral", class = "MONK", category = "groupcd" },
  { id = 31821, name = "Aura Mastery", class = "PALADIN", category = "groupcd" },
  { id = 391054, name = "Intercession", class = "PALADIN", category = "groupcd" },
  { id = 62618, name = "Power Word: Barrier", class = "PRIEST", category = "groupcd" },
  { id = 64843, name = "Divine Hymn", class = "PRIEST", category = "groupcd" },
  { id = 15286, name = "Vampiric Embrace", class = "PRIEST", category = "groupcd" },
  { id = 98008, name = "Spirit Link Totem", class = "SHAMAN", category = "groupcd" },
  { id = 108280, name = "Healing Tide Totem", class = "SHAMAN", category = "groupcd" },
  { id = 192077, name = "Wind Rush Totem", class = "SHAMAN", category = "groupcd" },
  { id = 20707, name = "Soulstone", class = "WARLOCK", category = "groupcd" },
  { id = 111771, name = "Demonic Gateway", class = "WARLOCK", category = "groupcd" },
  { id = 97462, name = "Rallying Cry", class = "WARRIOR", category = "groupcd" },
  --external
  { id = 102342, name = "Ironbark", class = "DRUID", category = "external" },
  { id = 29166, name = "Innervate", class = "DRUID", category = "external" },
  { id = 357170, name = "Time Dilation", class = "EVOKER", category = "external" },
  { id = 360827, name = "Blistering Scales", class = "EVOKER", category = "external" },
  { id = 370665, name = "Rescue", class = "EVOKER", category = "external" },
  { id = 53480, name = "Roar of Sacrifice", class = "HUNTER", category = "external" },
  { id = 116849, name = "Life Cocoon", class = "MONK", category = "external" },
  { id = 116841, name = "Tiger's Lust", class = "MONK", category = "external" },
  { id = 1022, name = "Blessing of Protection", class = "PALADIN", category = "external" },
  { id = 6940, name = "Blessing of Sacrifice", class = "PALADIN", category = "external" },
  { id = 204018, name = "Blessing of Spellwarding", class = "PALADIN", category = "external" },
  { id = 1044, name = "Blessing of Freedom", class = "PALADIN", category = "external" },
  { id = 633, name = "Lay on Hands", class = "PALADIN", category = "external" },
  { id = 33206, name = "Pain Suppression", class = "PRIEST", category = "external" },
  { id = 47788, name = "Guardian Spirit", class = "PRIEST", category = "external" },
  { id = 10060, name = "Power Infusion", class = "PRIEST", category = "external" },
  { id = 73325, name = "Leap of Faith", class = "PRIEST", category = "external" },
  { id = 3411, name = "Intervene", class = "WARRIOR", category = "external" },
  { id = 1244088, name = "Interpose", class = "WARRIOR", category = "external" },
  --defensive
  { id = 48707, name = "Anti-Magic Shell", class = "DEATHKNIGHT", category = "defensive" },
  { id = 48792, name = "Icebound Fortitude", class = "DEATHKNIGHT", category = "defensive" },
  { id = 55233, name = "Vampiric Blood", class = "DEATHKNIGHT", category = "defensive" },
  { id = 49028, name = "Dancing Rune Weapon", class = "DEATHKNIGHT", category = "defensive" },
  { id = 48743, name = "Death Pact", class = "DEATHKNIGHT", category = "defensive" },
  { id = 49039, name = "Lichborne", class = "DEATHKNIGHT", category = "defensive" },
  { id = 198589, name = "Blur", class = "DEMONHUNTER", category = "defensive" },
  { id = 187827, name = "Metamorphosis", class = "DEMONHUNTER", category = "defensive" },
  { id = 204021, name = "Fiery Brand", class = "DEMONHUNTER", category = "defensive" },
  { id = 203720, name = "Demon Spikes", class = "DEMONHUNTER", category = "defensive" },
  { id = 22812, name = "Barkskin", class = "DRUID", category = "defensive" },
  { id = 61336, name = "Survival Instincts", class = "DRUID", category = "defensive" },
  { id = 22842, name = "Frenzied Regeneration", class = "DRUID", category = "defensive" },
  { id = 192081, name = "Ironfur", class = "DRUID", category = "defensive" },
  { id = 363916, name = "Obsidian Scales", class = "EVOKER", category = "defensive" },
  { id = 186265, name = "Aspect of the Turtle", class = "HUNTER", category = "defensive" },
  { id = 264735, name = "Survival of the Fittest", class = "HUNTER", category = "defensive" },
  { id = 109304, name = "Exhilaration", class = "HUNTER", category = "defensive" },
  { id = 45438, name = "Ice Block", class = "MAGE", category = "defensive" },
  { id = 414659, name = "Ice Cold", class = "MAGE", category = "defensive" },
  { id = 11426, name = "Ice Barrier", class = "MAGE", category = "defensive" },
  { id = 235313, name = "Blazing Barrier", class = "MAGE", category = "defensive" },
  { id = 235450, name = "Prismatic Barrier", class = "MAGE", category = "defensive" },
  { id = 342245, name = "Alter Time", class = "MAGE", category = "defensive" },
  { id = 55342, name = "Mirror Image", class = "MAGE", category = "defensive" },
  { id = 110959, name = "Greater Invisibility", class = "MAGE", category = "defensive" },
  { id = 115203, name = "Fortifying Brew", class = "MONK", category = "defensive" },
  { id = 322507, name = "Celestial Brew", class = "MONK", category = "defensive" },
  { id = 1241059, name = "Celestial Infusion", class = "MONK", category = "defensive" },
  { id = 119582, name = "Purifying Brew", class = "MONK", category = "defensive" },
  { id = 122470, name = "Touch of Karma", class = "MONK", category = "defensive" },
  { id = 642, name = "Divine Shield", class = "PALADIN", category = "defensive" },
  { id = 498, name = "Divine Protection", class = "PALADIN", category = "defensive" },
  { id = 31850, name = "Ardent Defender", class = "PALADIN", category = "defensive" },
  { id = 86659, name = "Guardian of Ancient Kings", class = "PALADIN", category = "defensive" },
  { id = 389539, name = "Sentinel", class = "PALADIN", category = "defensive" },
  { id = 19236, name = "Desperate Prayer", class = "PRIEST", category = "defensive" },
  { id = 47585, name = "Dispersion", class = "PRIEST", category = "defensive" },
  { id = 586, name = "Fade", class = "PRIEST", category = "defensive" },
  { id = 5277, name = "Evasion", class = "ROGUE", category = "defensive" },
  { id = 31224, name = "Cloak of Shadows", class = "ROGUE", category = "defensive" },
  { id = 1966, name = "Feint", class = "ROGUE", category = "defensive" },
  { id = 185311, name = "Crimson Vial", class = "ROGUE", category = "defensive" },
  { id = 108271, name = "Astral Shift", class = "SHAMAN", category = "defensive" },
  { id = 104773, name = "Unending Resolve", class = "WARLOCK", category = "defensive" },
  { id = 108416, name = "Dark Pact", class = "WARLOCK", category = "defensive" },
  { id = 871, name = "Shield Wall", class = "WARRIOR", category = "defensive" },
  { id = 118038, name = "Die by the Sword", class = "WARRIOR", category = "defensive" },
  { id = 184364, name = "Enraged Regeneration", class = "WARRIOR", category = "defensive" },
  { id = 23920, name = "Spell Reflection", class = "WARRIOR", category = "defensive" },
  { id = 2565, name = "Shield Block", class = "WARRIOR", category = "defensive" },
  { id = 190456, name = "Ignore Pain", class = "WARRIOR", category = "defensive" },
  --cc
  { id = 221562, name = "Asphyxiate", class = "DEATHKNIGHT", category = "cc" },
  { id = 207167, name = "Blinding Sleet", class = "DEATHKNIGHT", category = "cc" },
  { id = 108199, name = "Gorefiend's Grasp", class = "DEATHKNIGHT", category = "cc" },
  { id = 49576, name = "Death Grip", class = "DEATHKNIGHT", category = "cc" },
  { id = 1263569, name = "Abomination Limb", class = "DEATHKNIGHT", category = "cc" },
  { id = 179057, name = "Chaos Nova", class = "DEMONHUNTER", category = "cc" },
  { id = 207684, name = "Sigil of Misery", class = "DEMONHUNTER", category = "cc" },
  { id = 202138, name = "Sigil of Chains", class = "DEMONHUNTER", category = "cc" },
  { id = 217832, name = "Imprison", class = "DEMONHUNTER", category = "cc" },
  { id = 1234195, name = "Void Nova", class = "DEMONHUNTER", category = "cc" },
  { id = 202137, name = "Sigil of Silence", class = "DEMONHUNTER", category = "cc" },
  { id = 5211, name = "Mighty Bash", class = "DRUID", category = "cc" },
  { id = 99, name = "Incapacitating Roar", class = "DRUID", category = "cc" },
  { id = 132469, name = "Typhoon", class = "DRUID", category = "cc" },
  { id = 102793, name = "Ursol's Vortex", class = "DRUID", category = "cc" },
  { id = 102359, name = "Mass Entanglement", class = "DRUID", category = "cc" },
  { id = 2637, name = "Hibernate", class = "DRUID", category = "cc" },
  { id = 33786, name = "Cyclone", class = "DRUID", category = "cc" },
  { id = 339, name = "Entangling Roots", class = "DRUID", category = "cc" },
  { id = 22570, name = "Maim", class = "DRUID", category = "cc" },
  { id = 360806, name = "Sleep Walk", class = "EVOKER", category = "cc" },
  { id = 358385, name = "Landslide", class = "EVOKER", category = "cc" },
  { id = 368970, name = "Tail Swipe", class = "EVOKER", category = "cc" },
  { id = 357214, name = "Wing Buffet", class = "EVOKER", category = "cc" },
  { id = 187650, name = "Freezing Trap", class = "HUNTER", category = "cc" },
  { id = 19577, name = "Intimidation", class = "HUNTER", category = "cc" },
  { id = 474421, name = "Intimidation", class = "HUNTER", category = "cc" },
  { id = 109248, name = "Binding Shot", class = "HUNTER", category = "cc" },
  { id = 187698, name = "Tar Trap", class = "HUNTER", category = "cc" },
  { id = 118, name = "Polymorph", class = "MAGE", category = "cc" },
  { id = 31661, name = "Dragon's Breath", class = "MAGE", category = "cc" },
  { id = 157980, name = "Supernova", class = "MAGE", category = "cc" },
  { id = 157997, name = "Ice Nova", class = "MAGE", category = "cc" },
  { id = 113724, name = "Ring of Frost", class = "MAGE", category = "cc" },
  { id = 383121, name = "Mass Polymorph", class = "MAGE", category = "cc" },
  { id = 122, name = "Frost Nova", class = "MAGE", category = "cc" },
  { id = 119381, name = "Leg Sweep", class = "MONK", category = "cc" },
  { id = 115078, name = "Paralysis", class = "MONK", category = "cc" },
  { id = 116844, name = "Ring of Peace", class = "MONK", category = "cc" },
  { id = 198898, name = "Song of Chi-Ji", class = "MONK", category = "cc" },
  { id = 853, name = "Hammer of Justice", class = "PALADIN", category = "cc" },
  { id = 115750, name = "Blinding Light", class = "PALADIN", category = "cc" },
  { id = 10326, name = "Turn Evil", class = "PALADIN", category = "cc" },
  { id = 8122, name = "Psychic Scream", class = "PRIEST", category = "cc" },
  { id = 88625, name = "Holy Word: Chastise", class = "PRIEST", category = "cc" },
  { id = 605, name = "Mind Control", class = "PRIEST", category = "cc" },
  { id = 205364, name = "Dominate Mind", class = "PRIEST", category = "cc" },
  { id = 9484, name = "Shackle Horror", class = "PRIEST", category = "cc" },
  { id = 408, name = "Kidney Shot", class = "ROGUE", category = "cc" },
  { id = 1833, name = "Cheap Shot", class = "ROGUE", category = "cc" },
  { id = 2094, name = "Blind", class = "ROGUE", category = "cc" },
  { id = 1776, name = "Gouge", class = "ROGUE", category = "cc" },
  { id = 6770, name = "Sap", class = "ROGUE", category = "cc" },
  { id = 192058, name = "Capacitor Totem", class = "SHAMAN", category = "cc" },
  { id = 51514, name = "Hex", class = "SHAMAN", category = "cc" },
  { id = 51490, name = "Thunderstorm", class = "SHAMAN", category = "cc" },
  { id = 51485, name = "Earthgrab Totem", class = "SHAMAN", category = "cc" },
  { id = 2484, name = "Earthbind Totem", class = "SHAMAN", category = "cc" },
  { id = 30283, name = "Shadowfury", class = "WARLOCK", category = "cc" },
  { id = 5484, name = "Howl of Terror", class = "WARLOCK", category = "cc" },
  { id = 6789, name = "Mortal Coil", class = "WARLOCK", category = "cc" },
  { id = 5782, name = "Fear", class = "WARLOCK", category = "cc" },
  { id = 710, name = "Banish", class = "WARLOCK", category = "cc" },
  { id = 46968, name = "Shockwave", class = "WARRIOR", category = "cc" },
  { id = 107570, name = "Storm Bolt", class = "WARRIOR", category = "cc" },
  { id = 5246, name = "Intimidating Shout", class = "WARRIOR", category = "cc" },
  { id = 12323, name = "Piercing Howl", class = "WARRIOR", category = "cc" },
  --interrupt
  { id = 47528, name = "Mind Freeze", class = "DEATHKNIGHT", category = "interrupt" },
  { id = 183752, name = "Disrupt", class = "DEMONHUNTER", category = "interrupt" },
  { id = 106839, name = "Skull Bash", class = "DRUID", category = "interrupt" },
  { id = 78675, name = "Solar Beam", class = "DRUID", category = "interrupt" },
  { id = 351338, name = "Quell", class = "EVOKER", category = "interrupt" },
  { id = 147362, name = "Counter Shot", class = "HUNTER", category = "interrupt" },
  { id = 187707, name = "Muzzle", class = "HUNTER", category = "interrupt" },
  { id = 2139, name = "Counterspell", class = "MAGE", category = "interrupt" },
  { id = 116705, name = "Spear Hand Strike", class = "MONK", category = "interrupt" },
  { id = 96231, name = "Rebuke", class = "PALADIN", category = "interrupt" },
  { id = 31935, name = "Avenger's Shield", class = "PALADIN", category = "interrupt" },
  { id = 15487, name = "Silence", class = "PRIEST", category = "interrupt" },
  { id = 1766, name = "Kick", class = "ROGUE", category = "interrupt" },
  { id = 57994, name = "Wind Shear", class = "SHAMAN", category = "interrupt" },
  { id = 19647, name = "Spell Lock", class = "WARLOCK", category = "interrupt" },
  { id = 89766, name = "Axe Toss", class = "WARLOCK", category = "interrupt" },
  { id = 6552, name = "Pummel", class = "WARRIOR", category = "interrupt" },
  { id = 386071, name = "Disrupting Shout", class = "WARRIOR", category = "interrupt" },
  --dispel
  { id = 278326, name = "Consume Magic", class = "DEMONHUNTER", category = "dispel" },
  { id = 88423, name = "Nature's Cure", class = "DRUID", category = "dispel" },
  { id = 2782, name = "Remove Corruption", class = "DRUID", category = "dispel" },
  { id = 2908, name = "Soothe", class = "DRUID", category = "dispel" },
  { id = 372048, name = "Oppressing Roar", class = "EVOKER", category = "dispel" },
  { id = 360823, name = "Naturalize", class = "EVOKER", category = "dispel" },
  { id = 365585, name = "Expunge", class = "EVOKER", category = "dispel" },
  { id = 374251, name = "Cauterizing Flame", class = "EVOKER", category = "dispel" },
  { id = 19801, name = "Tranquilizing Shot", class = "HUNTER", category = "dispel" },
  { id = 475, name = "Remove Curse", class = "MAGE", category = "dispel" },
  { id = 30449, name = "Spellsteal", class = "MAGE", category = "dispel" },
  { id = 115450, name = "Detox", class = "MONK", category = "dispel" },
  { id = 4987, name = "Cleanse", class = "PALADIN", category = "dispel" },
  { id = 213644, name = "Cleanse Toxins", class = "PALADIN", category = "dispel" },
  { id = 527, name = "Purify", class = "PRIEST", category = "dispel" },
  { id = 213634, name = "Purify Disease", class = "PRIEST", category = "dispel" },
  { id = 528, name = "Dispel Magic", class = "PRIEST", category = "dispel" },
  { id = 32375, name = "Mass Dispel", class = "PRIEST", category = "dispel" },
  { id = 5938, name = "Shiv", class = "ROGUE", category = "dispel" },
  { id = 77130, name = "Purify Spirit", class = "SHAMAN", category = "dispel" },
  { id = 51886, name = "Cleanse Spirit", class = "SHAMAN", category = "dispel" },
  { id = 370, name = "Purge", class = "SHAMAN", category = "dispel" },
  { id = 378773, name = "Greater Purge", class = "SHAMAN", category = "dispel" },
  { id = 383013, name = "Poison Cleansing Totem", class = "SHAMAN", category = "dispel" },
  { id = 19505, name = "Devour Magic", class = "WARLOCK", category = "dispel" },
  { id = 89808, name = "Singe Magic", class = "WARLOCK", category = "dispel" },
}
