---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Nnogga.
--- DateTime: 25.07.2018 08:59
---
---Tracks spells casted by enemies and adds them to the dataset
---
local db
local f

MethodDungeonTools.DataCollection = {}
local DC = MethodDungeonTools.DataCollection
function DC:Init()
    db = MethodDungeonTools:GetDB()
    db.dataCollection = db.dataCollection or {}
    f = CreateFrame("Frame")
    f:RegisterEvent("COMBAT_LOG_EVENT_UNFILTERED")
    f:SetScript("OnEvent", function(self, event, ...)
        return DC[event](self,...)
    end)
    --add spells from db to dungeonEnemies
    for i=15,24 do
        if db.dataCollection[i] then
            for id,spells in pairs(db.dataCollection[i]) do
                local enemies = MethodDungeonTools.dungeonEnemies[i]
                for enemyIdx,enemy in pairs(enemies) do
                    if enemy.id == id then
                        enemy.spells = enemy.spells or {}
                        for spellId,_ in pairs(spells) do
                            enemy.spells[spellId] = true
                        end
                    end

                end
            end
        end
    end

end

local trackedEvents = {
    ["SPELL_CAST_SUCCESS"]=true,
    ["SPELL_CAST_START"]=true,
    ["SPELL_MISSED"]=true,
    ["SPELL_DAMAGE"]=true,
    ["SPELL_AURA_REMOVED"]=true,
    ["SPELL_AURA_APPLIED"]=true,
}
function DC.COMBAT_LOG_EVENT_UNFILTERED(self,...)
    local timestamp,subevent,hideCaster,sourceGUID,sourceName,sourceFlags,sourceRaidFlags,destGUID,destName,destFlags,destRaidFlags,spellId,spellName,spellSchool = CombatLogGetCurrentEventInfo()
    if trackedEvents[subevent] then
        local unitType,_,serverId,instanceId,zoneId,id,spawnUid = strsplit("-", sourceGUID)
        id = tonumber(id)
        --dungeon
        for i=15,24 do
            local enemies = MethodDungeonTools.dungeonEnemies[i]
            --enemy
            for enemyIdx,enemy in pairs(enemies) do
                if enemy.id == id then
                    db.dataCollection[i] = db.dataCollection[i] or {}
                    db.dataCollection[i][id] = db.dataCollection[i][id] or {}
                    db.dataCollection[i][id][spellId] = true
                    enemy.spells = enemy.spells or {}
                    enemy.spells[spellId] = true
                    break
                end

            end

        end
    end

end


