---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Nnogga.
--- DateTime: 09.07.2018 07:35
---
local MDT = MethodDungeonTools
local AceGUI = LibStub("AceGUI-3.0")
local db

local tinsert,Model_Reset = table.insert,Model_Reset

local currentTab = "tab1"
local function MakeEnemeyInfoFrame()
    --frame
    local f = AceGUI:Create("Frame")
    f:SetTitle("Enemy Info")
    f:EnableResize(false)
    f.frame:SetMovable(false)
    function f.frame:StartMoving() end
    f:SetLayout("Fill")
    f:SetCallback("OnClose", function(widget)

    end)
    f.frame:SetAllPoints(MethodDungeonToolsScrollFrame)
    MethodDungeonTools:FixAceGUIShowHide(f)

    --tabGroup
    f.tabGroup = AceGUI:Create("TabGroup")
    local tabGroup = f.tabGroup
    tabGroup:SetTabs(
            {
                {text="Enemy Info", value="tab1"},
                {text="Damage Calc", value="tab2"},
            }
    )
    tabGroup:SetLayout("Flow")
    f:AddChild(tabGroup)

    --EnemyInfo
    local function DrawGroup1(container)

        ---LEFT
        local leftContainer = AceGUI:Create("SimpleGroup")
        leftContainer.frame:SetBackdropColor(1,1,1,0)
        leftContainer:SetWidth(container.frame:GetWidth()/2)
        leftContainer:SetHeight(container.frame:GetHeight())

        --enemyDropDown
        f.enemyDropDown = AceGUI:Create("Dropdown")
        local enemyDropDown = f.enemyDropDown
        enemyDropDown:SetCallback("OnValueChanged", function(widget,callbackName,key)
            MDT:UpdateEnemyInfoFrame(key)
        end)

        --model
        f.model = f.model or CreateFrame("PlayerModel", nil, f.frame,"ModelWithControlsTemplate")
        local model = f.model
        --ViragDevTool_AddData(model)
        model:SetFrameLevel(1)
        model:SetSize(300,300)
        model:SetScript("OnEnter",nil)
        model:SetFrameLevel(15)
        model:Show()
        local modelContainer = AceGUI:Create("SimpleGroup")
        modelContainer.frame:SetBackdropColor(1,1,1,0)
        modelContainer:SetWidth(300)
        modelContainer:SetHeight(300)
        modelContainer:SetLayout("Flow")
        local modelDummyIcon = AceGUI:Create("Icon")
        modelDummyIcon:SetImageSize(350, 350)
        modelDummyIcon:SetDisabled(true)
        modelContainer:AddChild(modelDummyIcon)
        model:SetPoint("TOP",modelContainer.frame,"TOP",0,0)
        MethodDungeonTools:FixAceGUIShowHide(model,modelContainer.frame,true)

        leftContainer:AddChild(enemyDropDown)
        leftContainer:AddChild(modelContainer)

        ---MIDDLE


        ---RIGHT


        container:AddChild(leftContainer)
    end

    --Damage Calc
    local function DrawGroup2(container)

    end


    -- Callback function for OnGroupSelected
    local function SelectGroup(container, event, group)
        container:ReleaseChildren()
        if group == "tab1" then
            DrawGroup1(container)
        elseif group == "tab2" then
            DrawGroup2(container)
        end
        currentTab = group
    end
    tabGroup:SetCallback("OnGroupSelected", SelectGroup)
    tabGroup:SelectTab(currentTab)

    return f
end

function MDT:UpdateEnemyInfoFrame(enemyIdx)
    local data = MDT.dungeonEnemies[db.currentDungeonIdx][enemyIdx]
    local f = MDT.EnemyInfoFrame
    f:SetTitle(data.name)
    f.model:SetDisplayInfo(data.displayId)
    Model_Reset(f.model)

    local enemies = {}
    for mobIdx,edata in ipairs(MDT.dungeonEnemies[db.currentDungeonIdx]) do
        tinsert(enemies,mobIdx,edata.name)
    end
    f.enemyDropDown:SetList(enemies)
    f.enemyDropDown:SetValue(enemyIdx)

end

function MDT:ShowEnemyInfoFrame(blip)
    db = MDT:GetDB()
    MDT.EnemyInfoFrame = MDT.EnemyInfoFrame or MakeEnemeyInfoFrame()
    MDT:UpdateEnemyInfoFrame(blip.enemyIdx)
    MDT.EnemyInfoFrame:Show()
end
