---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Nnogga.
--- DateTime: 24.07.2018 04:05
---
local displayIdOverrides = {

}
do
    for dungeonIdx,enemies in pairs(MethodDungeonTools.dungeonEnemies) do
        for enemyIdx,data in pairs(enemies) do
            if displayIdOverrides[data.id] then
                data.displayId = displayIdOverrides[data.id]
            end
        end
    end
end