local addonName = ...
local MDT = MDT
local L = MDT.L
local dungeonIndex = 103
MDT.dungeonList[dungeonIndex] = L["Black Rook Hold"]
MDT.mapInfo[dungeonIndex] = {

};
--TODO: add zoneIds

local function getSublevelMap(frame, sublevel)
  for i = 1, 12 do
    if frame["mapPanelTile"..i] then
      frame["mapPanelTile"..i]:Hide()
    end
  end
  for i = 1, 10 do
    for j = 1, 15 do
      local fileSuffix = (i - 1) * 15 + j
      local texName = 'Interface\\AddOns\\'..addonName..'\\Textures\\Upscaled\\BlackrookHold\\'..sublevel..'_'..fileSuffix..".png"
      local tile = frame["largeMapPanelTile"..i..j]
      tile:SetTexture(texName)
      tile:Show()
    end
  end
end

MDT.dungeonMaps[dungeonIndex] = {
  [0] = "",
  [1] = getSublevelMap,

}

MDT.dungeonSubLevels[dungeonIndex] = {
  [1] = L["Black Rook Hold"],
}

MDT.dungeonTotalCount[dungeonIndex] = { normal = 312, teeming = 1000, teemingEnabled = true }

MDT.mapPOIs[dungeonIndex] = {};

MDT.dungeonEnemies[dungeonIndex] = {
  [1] = {
    ["clones"] = {
      [1] = {
        ["x"] = 20,
        ["y"] = -95.0,
        ["sublevel"] = 1,
        ["g"] = 1,
      },
      [2] = {
        ["x"] = 20,
        ["y"] = -140.0,
        ["sublevel"] = 1,
        ["g"] = 4,
      },
      [3] = {
        ["x"] = 20,
        ["y"] = -215.0,
        ["sublevel"] = 1,
        ["g"] = 9,
      },
    },
    ["name"] = "Troubled Soul",
    ["id"] = 98362,
    ["health"] = 197601,
    ["level"] = 70,
    ["count"] = 0,
    ["displayId"] = 65812,
    ["creatureType"] = "Undead",
    ["scale"] = 1,
  },
  [2] = {
    ["clones"] = {
      [1] = {
        ["x"] = 20,
        ["y"] = -110.0,
        ["sublevel"] = 1,
        ["g"] = 2,
      },
      [2] = {
        ["x"] = 23,
        ["y"] = -140.0,
        ["sublevel"] = 1,
        ["g"] = 4,
      },
      [3] = {
        ["x"] = 20,
        ["y"] = -170.0,
        ["sublevel"] = 1,
        ["g"] = 6,
      },
      [4] = {
        ["x"] = 20,
        ["y"] = -185.0,
        ["sublevel"] = 1,
        ["g"] = 7,
      },
    },
    ["name"] = "Ghostly Protector",
    ["id"] = 98368,
    ["health"] = 1580808,
    ["level"] = 71,
    ["count"] = 4,
    ["displayId"] = 65786,
    ["creatureType"] = "Undead",
    ["scale"] = 1,
  },
  [3] = {
    ["clones"] = {
      [1] = {
        ["x"] = 23,
        ["y"] = -110.0,
        ["sublevel"] = 1,
        ["g"] = 2,
      },
      [2] = {
        ["x"] = 26,
        ["y"] = -110.0,
        ["sublevel"] = 1,
        ["g"] = 2,
      },
      [3] = {
        ["x"] = 20,
        ["y"] = -125.0,
        ["sublevel"] = 1,
        ["g"] = 3,
      },
      [4] = {
        ["x"] = 26,
        ["y"] = -140.0,
        ["sublevel"] = 1,
        ["g"] = 4,
      },
      [5] = {
        ["x"] = 20,
        ["y"] = -155.0,
        ["sublevel"] = 1,
        ["g"] = 5,
      },
      [6] = {
        ["x"] = 23,
        ["y"] = -155.0,
        ["sublevel"] = 1,
        ["g"] = 5,
      },
      [7] = {
        ["x"] = 23,
        ["y"] = -170.0,
        ["sublevel"] = 1,
        ["g"] = 6,
      },
      [8] = {
        ["x"] = 26,
        ["y"] = -170.0,
        ["sublevel"] = 1,
        ["g"] = 6,
      },
      [9] = {
        ["x"] = 23,
        ["y"] = -185.0,
        ["sublevel"] = 1,
        ["g"] = 7,
      },
      [10] = {
        ["x"] = 20,
        ["y"] = -200.0,
        ["sublevel"] = 1,
        ["g"] = 8,
      },
      [11] = {
        ["x"] = 23,
        ["y"] = -200.0,
        ["sublevel"] = 1,
        ["g"] = 8,
      },
    },
    ["name"] = "Ghostly Retainer",
    ["id"] = 98366,
    ["health"] = 988005,
    ["level"] = 70,
    ["count"] = 4,
    ["displayId"] = 65785,
    ["creatureType"] = "Undead",
    ["scale"] = 1,
  },
  [4] = {
    ["clones"] = {
      [1] = {
        ["x"] = 29,
        ["y"] = -110.0,
        ["sublevel"] = 1,
        ["g"] = 2,
      },
      [2] = {
        ["x"] = 23,
        ["y"] = -125.0,
        ["sublevel"] = 1,
        ["g"] = 3,
      },
      [3] = {
        ["x"] = 26,
        ["y"] = -125.0,
        ["sublevel"] = 1,
        ["g"] = 3,
      },
      [4] = {
        ["x"] = 29,
        ["y"] = -140.0,
        ["sublevel"] = 1,
        ["g"] = 4,
      },
      [5] = {
        ["x"] = 29,
        ["y"] = -170.0,
        ["sublevel"] = 1,
        ["g"] = 6,
      },
      [6] = {
        ["x"] = 26,
        ["y"] = -185.0,
        ["sublevel"] = 1,
        ["g"] = 7,
      },
      [7] = {
        ["x"] = 26,
        ["y"] = -200.0,
        ["sublevel"] = 1,
        ["g"] = 8,
      },
    },
    ["name"] = "Ghostly Councilor",
    ["id"] = 98370,
    ["health"] = 988005,
    ["level"] = 70,
    ["count"] = 4,
    ["displayId"] = 65787,
    ["creatureType"] = "Undead",
    ["scale"] = 1,
  },
  [5] = {
    ["clones"] = {
      [1] = {
        ["x"] = 32,
        ["y"] = -140.0,
        ["sublevel"] = 1,
        ["g"] = 4,
      },
    },
    ["name"] = "Lady Velandras Ravencrest",
    ["id"] = 98538,
    ["health"] = 1565000,
    ["level"] = 71,
    ["count"] = 10,
    ["displayId"] = 65833,
    ["creatureType"] = "Undead",
    ["scale"] = 1,
  },
  [6] = {
    ["clones"] = {
      [1] = {
        ["x"] = 29,
        ["y"] = -200.0,
        ["sublevel"] = 1,
        ["g"] = 8,
      },
    },
    ["name"] = "Lord Etheldrin Ravencrest",
    ["id"] = 98521,
    ["health"] = 2371212,
    ["level"] = 71,
    ["count"] = 10,
    ["displayId"] = 65814,
    ["creatureType"] = "Undead",
    ["scale"] = 1,
  },
  [7] = {
    ["clones"] = {
      [1] = {
        ["x"] = 23,
        ["y"] = -215.0,
        ["sublevel"] = 1,
        ["g"] = 9,
      },
    },
    ["isBoss"] = true,
    ["encounterID"] = 1518,
    ["instanceID"] = 740,
    ["name"] = "Amalgam of Souls",
    ["id"] = 98542,
    ["health"] = 6916035,
    ["level"] = 72,
    ["count"] = 0,
    ["displayId"] = 65837,
    ["creatureType"] = "Undead",
    ["scale"] = 1,
  },
  [8] = {
    ["clones"] = {
      [1] = {
        ["x"] = 20,
        ["y"] = -230.0,
        ["sublevel"] = 1,
        ["g"] = 10,
      },
      [2] = {
        ["x"] = 23,
        ["y"] = -230.0,
        ["sublevel"] = 1,
        ["g"] = 10,
      },
      [3] = {
        ["x"] = 26,
        ["y"] = -230.0,
        ["sublevel"] = 1,
        ["g"] = 10,
      },
      [4] = {
        ["x"] = 29,
        ["y"] = -230.0,
        ["sublevel"] = 1,
        ["g"] = 10,
      },
      [5] = {
        ["x"] = 32,
        ["y"] = -230.0,
        ["sublevel"] = 1,
        ["g"] = 10,
      },
      [6] = {
        ["x"] = 20,
        ["y"] = -95.0,
        ["sublevel"] = 1,
        ["g"] = 11,
      },
      [7] = {
        ["x"] = 23,
        ["y"] = -95.0,
        ["sublevel"] = 1,
        ["g"] = 11,
      },
      [8] = {
        ["x"] = 26,
        ["y"] = -95.0,
        ["sublevel"] = 1,
        ["g"] = 11,
      },
      [9] = {
        ["x"] = 29,
        ["y"] = -95.0,
        ["sublevel"] = 1,
        ["g"] = 11,
      },
      [10] = {
        ["x"] = 32,
        ["y"] = -95.0,
        ["sublevel"] = 1,
        ["g"] = 11,
      },
      [11] = {
        ["x"] = 35,
        ["y"] = -95.0,
        ["sublevel"] = 1,
        ["g"] = 11,
      },
      [12] = {
        ["x"] = 38,
        ["y"] = -95.0,
        ["sublevel"] = 1,
        ["g"] = 11,
      },
      [13] = {
        ["x"] = 41,
        ["y"] = -95.0,
        ["sublevel"] = 1,
        ["g"] = 11,
      },
      [14] = {
        ["x"] = 44,
        ["y"] = -95.0,
        ["sublevel"] = 1,
        ["g"] = 11,
      },
      [15] = {
        ["x"] = 47,
        ["y"] = -95.0,
        ["sublevel"] = 1,
        ["g"] = 11,
      },
      [16] = {
        ["x"] = 50,
        ["y"] = -95.0,
        ["sublevel"] = 1,
        ["g"] = 11,
      },
      [17] = {
        ["x"] = 164,
        ["y"] = -95.0,
        ["sublevel"] = 1,
        ["g"] = 11,
      },
      [18] = {
        ["x"] = 167,
        ["y"] = -95.0,
        ["sublevel"] = 1,
        ["g"] = 11,
      },
      [19] = {
        ["x"] = 170,
        ["y"] = -95.0,
        ["sublevel"] = 1,
        ["g"] = 11,
      },
    },
    ["name"] = "Rook Spiderling",
    ["id"] = 98677,
    ["health"] = 197601,
    ["level"] = 70,
    ["count"] = 1,
    ["displayId"] = 35688,
    ["creatureType"] = "Beast",
    ["scale"] = 1,
  },
  [9] = {
    ["clones"] = {
      [1] = {
        ["x"] = 173,
        ["y"] = -95.0,
        ["sublevel"] = 1,
        ["g"] = 11,
      },
    },
    ["name"] = "Rook Spinner",
    ["id"] = 98681,
    ["health"] = 1580808,
    ["level"] = 70,
    ["count"] = 6,
    ["displayId"] = 42742,
    ["creatureType"] = "Beast",
    ["scale"] = 1,
  },
  [10] = {
    ["clones"] = {
      [1] = {
        ["x"] = 131,
        ["y"] = -110.0,
        ["sublevel"] = 1,
        ["g"] = 12,
      },
      [2] = {
        ["x"] = 131,
        ["y"] = -125.0,
        ["sublevel"] = 1,
        ["g"] = 13,
      },
      [3] = {
        ["x"] = 131,
        ["y"] = -140.0,
        ["sublevel"] = 1,
        ["g"] = 14,
      },
      [4] = {
        ["x"] = 131,
        ["y"] = -200.0,
        ["sublevel"] = 1,
        ["g"] = 18,
      },
    },
    ["name"] = "Soul-Torn Champion",
    ["id"] = 98243,
    ["health"] = 1383207,
    ["level"] = 70,
    ["count"] = 4,
    ["displayId"] = 65762,
    ["creatureType"] = "Undead",
    ["scale"] = 1,
  },
  [11] = {
    ["clones"] = {
      [1] = {
        ["x"] = 134,
        ["y"] = -110.0,
        ["sublevel"] = 1,
        ["g"] = 12,
      },
      [2] = {
        ["x"] = 134,
        ["y"] = -140.0,
        ["sublevel"] = 1,
        ["g"] = 14,
      },
      [3] = {
        ["x"] = 131,
        ["y"] = -155.0,
        ["sublevel"] = 1,
        ["g"] = 15,
      },
      [4] = {
        ["x"] = 131,
        ["y"] = -170.0,
        ["sublevel"] = 1,
        ["g"] = 16,
      },
      [5] = {
        ["x"] = 131,
        ["y"] = -185.0,
        ["sublevel"] = 1,
        ["g"] = 17,
      },
      [6] = {
        ["x"] = 134,
        ["y"] = -185.0,
        ["sublevel"] = 1,
        ["g"] = 17,
      },
    },
    ["name"] = "Risen Scout",
    ["id"] = 98691,
    ["health"] = 889205,
    ["level"] = 70,
    ["count"] = 4,
    ["displayId"] = 65950,
    ["creatureType"] = "Undead",
    ["scale"] = 1,
  },
  [12] = {
    ["clones"] = {
      [1] = {
        ["x"] = 134,
        ["y"] = -125.0,
        ["sublevel"] = 1,
        ["g"] = 13,
      },
      [2] = {
        ["x"] = 137,
        ["y"] = -140.0,
        ["sublevel"] = 1,
        ["g"] = 14,
      },
      [3] = {
        ["x"] = 134,
        ["y"] = -170.0,
        ["sublevel"] = 1,
        ["g"] = 16,
      },
      [4] = {
        ["x"] = 137,
        ["y"] = -170.0,
        ["sublevel"] = 1,
        ["g"] = 16,
      },
      [5] = {
        ["x"] = 137,
        ["y"] = -185.0,
        ["sublevel"] = 1,
        ["g"] = 17,
      },
      [6] = {
        ["x"] = 140,
        ["y"] = -185.0,
        ["sublevel"] = 1,
        ["g"] = 17,
      },
      [7] = {
        ["x"] = 134,
        ["y"] = -200.0,
        ["sublevel"] = 1,
        ["g"] = 18,
      },
      [8] = {
        ["x"] = 137,
        ["y"] = -200.0,
        ["sublevel"] = 1,
        ["g"] = 18,
      },
    },
    ["name"] = "Risen Archer",
    ["id"] = 98275,
    ["health"] = 790404,
    ["level"] = 70,
    ["count"] = 4,
    ["displayId"] = 65743,
    ["creatureType"] = "Undead",
    ["scale"] = 1,
  },
  [13] = {
    ["clones"] = {
      [1] = {
        ["x"] = 137,
        ["y"] = -125.0,
        ["sublevel"] = 1,
        ["g"] = 13,
      },
      [2] = {
        ["x"] = 140,
        ["y"] = -170.0,
        ["sublevel"] = 1,
        ["g"] = 16,
      },
    },
    ["name"] = "Risen Arcanist",
    ["id"] = 98280,
    ["health"] = 790404,
    ["level"] = 70,
    ["count"] = 4,
    ["displayId"] = 65718,
    ["creatureType"] = "Undead",
    ["scale"] = 1,
  },
  [14] = {
    ["clones"] = {
      [1] = {
        ["x"] = 140,
        ["y"] = -125.0,
        ["sublevel"] = 1,
        ["g"] = 13,
      },
      [2] = {
        ["x"] = 143,
        ["y"] = -170.0,
        ["sublevel"] = 1,
        ["g"] = 16,
      },
    },
    ["name"] = "Arcane Minion",
    ["id"] = 101549,
    ["health"] = 247001,
    ["level"] = 70,
    ["count"] = 1,
    ["displayId"] = 67018,
    ["creatureType"] = "Aberration",
    ["scale"] = 1,
  },
  [15] = {
    ["clones"] = {
      [1] = {
        ["x"] = 134,
        ["y"] = -155.0,
        ["sublevel"] = 1,
        ["g"] = 15,
      },
    },
    ["name"] = "Risen Companion",
    ["id"] = 101839,
    ["health"] = 592803,
    ["level"] = 70,
    ["count"] = 4,
    ["displayId"] = 64620,
    ["creatureType"] = "Undead",
    ["scale"] = 1,
  },
  [16] = {
    ["clones"] = {
      [1] = {
        ["x"] = 143,
        ["y"] = -185.0,
        ["sublevel"] = 1,
        ["g"] = 17,
      },
    },
    ["name"] = "Commander Shemdah'sohn",
    ["id"] = 98706,
    ["health"] = 1580808,
    ["level"] = 71,
    ["count"] = 6,
    ["displayId"] = 65954,
    ["creatureType"] = "Undead",
    ["scale"] = 1,
  },
  [17] = {
    ["clones"] = {
      [1] = {
        ["x"] = 131,
        ["y"] = -215.0,
        ["sublevel"] = 1,
        ["g"] = 19,
      },
    },
    ["name"] = "Illysanna Ravencrest",
    ["id"] = 98696,
    ["health"] = 6125631,
    ["level"] = 72,
    ["count"] = 0,
    ["displayId"] = 65951,
    ["creatureType"] = "Demon",
    ["scale"] = 1,
  },
  [18] = {
    ["clones"] = {
      [1] = {
        ["x"] = 242,
        ["y"] = -95.0,
        ["sublevel"] = 1,
        ["g"] = 20,
      },
      [2] = {
        ["x"] = 245,
        ["y"] = -95.0,
        ["sublevel"] = 1,
        ["g"] = 20,
      },
      [3] = {
        ["x"] = 248,
        ["y"] = -95.0,
        ["sublevel"] = 1,
        ["g"] = 20,
      },
      [4] = {
        ["x"] = 251,
        ["y"] = -95.0,
        ["sublevel"] = 1,
        ["g"] = 20,
      },
      [5] = {
        ["x"] = 242,
        ["y"] = -110.0,
        ["sublevel"] = 1,
        ["g"] = 21,
      },
      [6] = {
        ["x"] = 242,
        ["y"] = -140.0,
        ["sublevel"] = 1,
        ["g"] = 23,
      },
      [7] = {
        ["x"] = 245,
        ["y"] = -140.0,
        ["sublevel"] = 1,
        ["g"] = 23,
      },
      [8] = {
        ["x"] = 242,
        ["y"] = -185.0,
        ["sublevel"] = 1,
        ["g"] = 26,
      },
      [9] = {
        ["x"] = 245,
        ["y"] = -185.0,
        ["sublevel"] = 1,
        ["g"] = 26,
      },
      [10] = {
        ["x"] = 248,
        ["y"] = -185.0,
        ["sublevel"] = 1,
        ["g"] = 26,
      },
      [11] = {
        ["x"] = 251,
        ["y"] = -185.0,
        ["sublevel"] = 1,
        ["g"] = 26,
      },
      [12] = {
        ["x"] = 254,
        ["y"] = -185.0,
        ["sublevel"] = 1,
        ["g"] = 26,
      },
      [13] = {
        ["x"] = 353,
        ["y"] = -95.0,
        ["sublevel"] = 1,
        ["g"] = 27,
      },
    },
    ["name"] = "Wyrmtongue Trickster",
    ["id"] = 98900,
    ["health"] = 395202,
    ["level"] = 70,
    ["count"] = 3,
    ["displayId"] = 64483,
    ["creatureType"] = "Demon",
    ["scale"] = 1,
  },
  [19] = {
    ["clones"] = {
      [1] = {
        ["x"] = 245,
        ["y"] = -110.0,
        ["sublevel"] = 1,
        ["g"] = 21,
      },
      [2] = {
        ["x"] = 248,
        ["y"] = -110.0,
        ["sublevel"] = 1,
        ["g"] = 21,
      },
      [3] = {
        ["x"] = 251,
        ["y"] = -110.0,
        ["sublevel"] = 1,
        ["g"] = 21,
      },
      [4] = {
        ["x"] = 254,
        ["y"] = -110.0,
        ["sublevel"] = 1,
        ["g"] = 21,
      },
      [5] = {
        ["x"] = 248,
        ["y"] = -140.0,
        ["sublevel"] = 1,
        ["g"] = 23,
      },
      [6] = {
        ["x"] = 251,
        ["y"] = -140.0,
        ["sublevel"] = 1,
        ["g"] = 23,
      },
      [7] = {
        ["x"] = 254,
        ["y"] = -140.0,
        ["sublevel"] = 1,
        ["g"] = 23,
      },
      [8] = {
        ["x"] = 242,
        ["y"] = -155.0,
        ["sublevel"] = 1,
        ["g"] = 24,
      },
      [9] = {
        ["x"] = 245,
        ["y"] = -155.0,
        ["sublevel"] = 1,
        ["g"] = 24,
      },
      [10] = {
        ["x"] = 242,
        ["y"] = -170.0,
        ["sublevel"] = 1,
        ["g"] = 25,
      },
      [11] = {
        ["x"] = 356,
        ["y"] = -95.0,
        ["sublevel"] = 1,
        ["g"] = 27,
      },
    },
    ["name"] = "Wyrmtongue Scavenger",
    ["id"] = 98792,
    ["health"] = 790404,
    ["level"] = 70,
    ["count"] = 3,
    ["displayId"] = 64476,
    ["creatureType"] = "Demon",
    ["scale"] = 1,
  },
  [20] = {
    ["clones"] = {
      [1] = {
        ["x"] = 242,
        ["y"] = -125.0,
        ["sublevel"] = 1,
        ["g"] = 22,
      },
      [2] = {
        ["x"] = 257,
        ["y"] = -185.0,
        ["sublevel"] = 1,
        ["g"] = 26,
      },
      [3] = {
        ["x"] = 260,
        ["y"] = -185.0,
        ["sublevel"] = 1,
        ["g"] = 26,
      },
    },
    ["name"] = "Wrathguard Bladelord",
    ["id"] = 98810,
    ["health"] = 1185606,
    ["level"] = 70,
    ["count"] = 6,
    ["displayId"] = 63994,
    ["creatureType"] = "Demon",
    ["scale"] = 1,
  },
  [21] = {
    ["clones"] = {
      [1] = {
        ["x"] = 245,
        ["y"] = -125.0,
        ["sublevel"] = 1,
        ["g"] = 22,
      },
      [2] = {
        ["x"] = 245,
        ["y"] = -170.0,
        ["sublevel"] = 1,
        ["g"] = 25,
      },
    },
    ["name"] = "Bloodscent Felhound",
    ["id"] = 98813,
    ["health"] = 691604,
    ["level"] = 70,
    ["count"] = 4,
    ["displayId"] = 65054,
    ["creatureType"] = "Demon",
    ["scale"] = 1,
  },
  [22] = {
    ["clones"] = {
      [1] = {
        ["x"] = 359,
        ["y"] = -95.0,
        ["sublevel"] = 1,
        ["g"] = 27,
      },
      [2] = {
        ["x"] = 353,
        ["y"] = -110.0,
        ["sublevel"] = 1,
        ["g"] = 28,
      },
      [3] = {
        ["x"] = 356,
        ["y"] = -110.0,
        ["sublevel"] = 1,
        ["g"] = 28,
      },
      [4] = {
        ["x"] = 359,
        ["y"] = -110.0,
        ["sublevel"] = 1,
        ["g"] = 28,
      },
    },
    ["name"] = "Felspite Dominator",
    ["id"] = 102788,
    ["health"] = 1580808,
    ["level"] = 71,
    ["count"] = 4,
    ["displayId"] = 5047,
    ["creatureType"] = "Demon",
    ["scale"] = 1,
  },
  [23] = {
    ["clones"] = {
      [1] = {
        ["x"] = 353,
        ["y"] = -125.0,
        ["sublevel"] = 1,
        ["g"] = 29,
      },
    },
    ["isBoss"] = true,
    ["encounterID"] = 1664,
    ["instanceID"] = 740,
    ["name"] = "Smashspite the Hateful",
    ["id"] = 98949,
    ["health"] = 6916035,
    ["level"] = 72,
    ["count"] = 0,
    ["displayId"] = 65304,
    ["creatureType"] = "Demon",
    ["scale"] = 1,
  },
  [24] = {
    ["clones"] = {
      [1] = {
        ["x"] = 353,
        ["y"] = -140.0,
        ["sublevel"] = 1,
        ["g"] = 30,
      },
      [2] = {
        ["x"] = 464,
        ["y"] = -110.0,
        ["sublevel"] = 1,
        ["g"] = 32,
      },
      [3] = {
        ["x"] = 464,
        ["y"] = -125.0,
        ["sublevel"] = 1,
        ["g"] = 33,
      },
      [4] = {
        ["x"] = 464,
        ["y"] = -140.0,
        ["sublevel"] = 1,
        ["g"] = 34,
      },
      [5] = {
        ["x"] = 467,
        ["y"] = -140.0,
        ["sublevel"] = 1,
        ["g"] = 34,
      },
    },
    ["name"] = "Risen Lancer",
    ["id"] = 102095,
    ["health"] = 1086806,
    ["level"] = 70,
    ["count"] = 4,
    ["displayId"] = 67478,
    ["creatureType"] = "Undead",
    ["scale"] = 1,
  },
  [25] = {
    ["clones"] = {
      [1] = {
        ["x"] = 356,
        ["y"] = -140.0,
        ["sublevel"] = 1,
        ["g"] = 30,
      },
      [2] = {
        ["x"] = 464,
        ["y"] = -95.0,
        ["sublevel"] = 1,
        ["g"] = 31,
      },
      [3] = {
        ["x"] = 467,
        ["y"] = -95.0,
        ["sublevel"] = 1,
        ["g"] = 31,
      },
      [4] = {
        ["x"] = 467,
        ["y"] = -110.0,
        ["sublevel"] = 1,
        ["g"] = 32,
      },
      [5] = {
        ["x"] = 467,
        ["y"] = -125.0,
        ["sublevel"] = 1,
        ["g"] = 33,
      },
      [6] = {
        ["x"] = 470,
        ["y"] = -140.0,
        ["sublevel"] = 1,
        ["g"] = 34,
      },
      [7] = {
        ["x"] = 473,
        ["y"] = -140.0,
        ["sublevel"] = 1,
        ["g"] = 34,
      },
    },
    ["name"] = "Risen Swordsman",
    ["id"] = 102094,
    ["health"] = 988005,
    ["level"] = 70,
    ["count"] = 4,
    ["displayId"] = 67488,
    ["creatureType"] = "Undead",
    ["scale"] = 1,
  },
  [26] = {
    ["clones"] = {
      [1] = {
        ["x"] = 575,
        ["y"] = -95.0,
        ["sublevel"] = 1,
        ["g"] = 35,
      },
    },
    ["name"] = "Kur'talos Ravencrest",
    ["id"] = 98965,
    ["health"] = 2371212,
    ["level"] = 72,
    ["count"] = 0,
    ["displayId"] = 66853,
    ["creatureType"] = "Undead",
    ["scale"] = 1,
  },
  [27] = {
    ["clones"] = {
      [1] = {
        ["x"] = 578,
        ["y"] = -95.0,
        ["sublevel"] = 1,
        ["g"] = 35,
      },
    },
    ["name"] = "Latosius",
    ["id"] = 98970,
    ["health"] = 2371212,
    ["level"] = 72,
    ["count"] = 0,
    ["displayId"] = 66032,
    ["creatureType"] = "Humanoid",
    ["scale"] = 1,
  },
  [28] = {
    ["clones"] = {
      [1] = {
        ["x"] = 575,
        ["y"] = -110.0,
        ["sublevel"] = 1,
        ["g"] = 36,
      },
    },
    ["name"] = "Stinging Swarm",
    ["id"] = 101008,
    ["health"] = 444602,
    ["level"] = 70,
    ["count"] = 0,
    ["displayId"] = 32542,
    ["creatureType"] = "Uncategorized",
    ["scale"] = 1,
  },
};
